services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: [ inception ]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$(cat /run/secrets/db_root_password) || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    secrets:
      - db_root_password
      - db_password
      - wp_admin_password
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks: [ inception ]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --allow-root --path=/var/www/html || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx
    container_name: nginx
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - "443:443"
    networks: [ inception ]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 10s
      timeout: 5s
      retries: 20
  
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yuewang/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yuewang/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/credentials.txt

networks:
  inception:
    driver: bridge
